### ISSUE TITLE
vesting ui is not available by link

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Bonfida/token-vesting#15]
it timeouts

https://vesting.bonfida.org/

**Comment by dzmitry-lahoda** [comment]
oh, available, seems like temp instability. is not it hosted of some static website?

**Comment by dr497** [comment]
It's a static website hosted on IPFS (`QmRLLPk4na76gyzwHKtDy9ADu9VA5kKozfzyWyDiK2KUbf`). Probably a temp node or gateway instability.
