### ISSUE TITLE
unable to understand token Account

### ISSUE THREAD

**Issue by Merrick17** [Bonfida/token-vesting#16]
hello i'm trying to execute the simple vesting code , i don't understand what the comment means with DESTINATION_TOKEN_ACCOUNT , 
becuase when retrieving info from web3 it returns an object with type AccountInfo not havinga  public key , please if someone could provide a full explanation !

**Comment by dr497** [comment]
Hey!

You can read about token accounts on Solana here https://spl.solana.com/token#creating-accounts

Also it's strongly recommended to always use [associated token accounts](https://spl.solana.com/associated-token-account)
