### ISSUE TITLE
Token Vesting Ui Issue

### ISSUE THREAD

**Issue by Fiverr-Coin-Hunter** [Bonfida/token-vesting#18]
How to create a vesting contract using ui ?
i didn't find that

**Comment by dr497** [comment]
To lock tokens please use directly the Rust CLI or JS library

**Comment by Fiverr-Coin-Hunter** [comment]
> To lock tokens please use directly the Rust CLI or JS library

where can i find the guide

**Comment by dr497** [comment]
You will find it here https://github.com/Bonfida/token-vesting/tree/master/js and here you will find an example of a linear unlock https://github.com/Bonfida/token-vesting/blob/master/js/src/dev.ts

**Comment by Fiverr-Coin-Hunter** [comment]
> You will find it here https://github.com/Bonfida/token-vesting/tree/master/js and here you will find an example of a linear unlock https://github.com/Bonfida/token-vesting/blob/master/js/src/dev.ts

there didn't have better guide

**Comment by islaperfito** [comment]
This doesn't work. Pls get this UI fixed

**Comment by dr497** [comment]
To lock tokens please use directly the Rust CLI or JS library:

- JS library: https://github.com/Bonfida/token-vesting/tree/master/js
- JS example: https://github.com/Bonfida/token-vesting/blob/master/js/src/dev.ts
- Rust CLI: https://github.com/Bonfida/token-vesting/tree/master/cli
