### ISSUE TITLE
Token Lock has disappeared from the UI

### ISSUE THREAD

**Issue by islaperfito** [Bonfida/token-vesting#19]
Why is it no longer possible to lock tokens here?
https://vesting.bonfida.org/#/

Now only possible to unlock, and change destination. The documentation you list is all outdated, and there is no explanation for why it is not longer possible to lock tokens. Please fix this. This was working fine just 2 months ago at https://vesting.bonfida.org/#/. There was "Lock" , "Unlock" , and "Change Destination"

Now, it only gives ability to "Unlock" and "Change Destination"

What is going on?

**Comment by dr497** [comment]
To lock tokens please use directly the Rust CLI or JS library:

- JS library: https://github.com/Bonfida/token-vesting/tree/master/js
- JS example: https://github.com/Bonfida/token-vesting/blob/master/js/src/dev.ts
- Rust CLI: https://github.com/Bonfida/token-vesting/tree/master/cli

**Comment by isla-chainalysis** [comment]
Why is it no longer available in the UI?
