### ISSUE TITLE
My question remains unanswered: Why was Lock option removed from the UI?

### ISSUE THREAD

**Issue by islaperfito** [Bonfida/token-vesting#20]
Please add this feature back.

**Comment by dr497** [comment]
There is no need for a UI as you can do it with JS or Rust

- JS library: https://github.com/Bonfida/token-vesting/tree/master/js
- JS example: https://github.com/Bonfida/token-vesting/blob/master/js/src/dev.ts
- Rust CLI: https://github.com/Bonfida/token-vesting/tree/master/cli

**Comment by isla-chainalysis** [comment]
Horrible oversight . Removing a feature from your UI without updating your documentation.

**Comment by islaperfito** [comment]
Horrible oversight . Removing a feature from your UI without updating your documentation.....

**Comment by dr497** [comment]
The documentation is up to date for both JS and Rust, it also contains details examples.

**Comment by islaperfito** [comment]
They do not work :(
