### ISSUE TITLE
Please add back "Lock" to Bonafida UI - Rust CLI does not work

### ISSUE THREAD

**Issue by islaperfito** [Bonfida/token-vesting#21]
I am not sure why the "Lock" option was removed from the UI, and I (and others!) are having trouble getting the Rust CLI to work. I've followed all steps in the documentation.

First, when attempting to get the ProgramID with this command (as listed in the documentation):
solana deploy ../program/target/deploy/token_vesting.so --url https://api.mainnet-beta.solana.com --config  /Users/myuser/.config/solana/id_owner.json   
                                                 
I get this error:

Error: Unable to open program file: No such file or directory (os error 2)

Secondly, when I attempt to lock tokens as so:

echo "RUST_BACKTRACE=1 ./target/debug/vesting-contract-cli    --url https://api.mainnet-beta.solana.com     --program_id XXXXX     create    --mint_address XXXXXX    --source_owner /Users/solana/me/myusers/keyfile.json   --source_token_address XXXXX    --destination_address XXXXX    --amounts 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,!     --release-times 1640890837,1640891837,1640892837,1640893837,1640894837,1640895837,1640896837,1640897837,1640898837,1640899837,1640900837,1640901837,1640902837,1640903837,1640904837,1640905837,1640906837,1640907837,1640908837,1640909837,1640910837,1640911837,1640912837,1640913837,!  --payer /Users/solana/me/myusers/keyfile.json"    --verbose | bash

I get this result:

The seed of the contract is: <CONTRACTSEED>
Please write it down as it is needed to interact with the contract.

Looks like it works, doesnt it?
When I search for the contract seed in your UI, it is nowhere to be found.

please add back the Lock option back to the UI.

**Comment by dr497** [comment]
Given the error message it looks like you have not compiled the program you are trying to deploy. Also the program is already deployed on mainnet with the ID `CChTq6PthWU82YZkbveA3WDf7s97BWhBK4Vx9bmsT743`. 

If you are not comfortable with the Solana CLI, deployment process and Rust I strongly recommend you to use the JS example instead: https://github.com/Bonfida/token-vesting/blob/master/js/src/dev.ts

**Comment by islaperfito** [comment]
This doesn't answer my question. I am trying to deploy a new program, and used CChTq6PthWU82YZkbveA3WDf7s97BWhBK4Vx9bmsT743 as an example.

" it looks like you have not compiled the program you are trying to deploy."
Then what step must I follow to get there?

stop closing my issues prematurely. My problem still stands and this shouldnt be closed

**Comment by islaperfito** [comment]
And whats your answer for returning a contact seed that doesn't exist?

The seed of the contract is: GcdayuLaLyrdmUu324nahyv33G5poQdLUEZ1nEytDin

It is non existent....

**Comment by islaperfito** [comment]
The steps you have listed in the RUST CLI documentation don't work

solana deploy ../program/target/deploy/token_vesting.so --url https://api.mainnet-beta.solana.com --config  ~/.config/solana/id_owner.json

**Error: Unable to open program file: No such file or directory (os error 2)**
