### ISSUE TITLE
Rust CLI Help

### ISSUE THREAD

**Issue by islaperfito** [Bonfida/token-vesting#22]
Following the instructions here:
https://github.com/Bonfida/token-vesting/tree/master/cli

I created the participants accounts. This step works fine

I deposited SOL into the id_owner account.

Next step says:
Deploy program and copy PROGRAM_ID.
`solana deploy ../program/target/deploy/token_vesting.so --url https://devnet.solana.com --config  ~/.config/solana/id_owner.json`

When I run this, I get this error
Error: Unable to open program file: No such file or directory (os error 2)

How to fix?

**Comment by dr497** [comment]
The error message is self explanatory `token_vesting.so` does not exist. You need to compile the program first before deploying it. 

Please read about the deployment process https://docs.solana.com/cli/deploy-a-program

Also note that you don't need to deploy the program as it's already deployed on devnet and mainnet

**Comment by islaperfito** [comment]
You should update your documentation.

**Comment by islaperfito** [comment]
Stop closing my issues!

**Comment by islaperfito** [comment]
Ever since your last commit the UI got destroyed
