### ISSUE TITLE
error compiling CLI - no method named `get_latest_blockhash` found for struct `RpcClient` in the current scope

### ISSUE THREAD

**Issue by alex-3881** [Bonfida/token-vesting#28]
when compiling CLI (`cargo build` in cli folder), build fails with the screenshoted error
![error](https://user-images.githubusercontent.com/78366335/148656717-3726f318-5532-4d84-a98c-458168942aff.png)

**Comment by alex-3881** [comment]
changes from 
let recent_blockhash = rpc_client.get_latest_blockhash().unwrap();
to
let recent_blockhash = rpc_client.get_recent_blockhash().unwrap().0;
on lines 88, 140, 183 seemed to fix it, everything compiled and seems to work

**Comment by dr497** [comment]
This should fix it https://github.com/Bonfida/token-vesting/commit/cea0793ca0a5e37cc3dd81d446b5630fdbf1ac1d

Thanks for opening the issue!
