### ISSUE TITLE
failed to send transaction: Transaction simulation failed...

### ISSUE THREAD

**Issue by dt1** [Bonfida/token-vesting#30]
I understand what the error is attempting to say, but the issue is, there is a brand new account every time I run `yarn dev`

as an example

`Vesting contract account pubkey:  6ddovVHQuvjyiPw2euE6Vhr9TJRHkozFxdrxLNDcP1qf
contract ID:  4K8hh4chgRegqJ9i3i9iTpjuMgSixmQn47GXWJwrduoL
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit. `

I've filled in all the fields in `src/dev.ts' with my own information, so presumably, it should not be creating a new account from nowhere. This continues to happen. Where are all of these coming from and how can I prevent this from continuing?

I'm writing it here because I don't know if this is a bug.

**Comment by dr497** [comment]
The `dev.ts` file works fine. The error `Attempt to debit an account but found no record of a prior credit.` means that you don't have SOL in the wallet you are using to sign and send the transaction

**Comment by dr497** [comment]
It's the wallet you are using to sign the tx that needs SOL i.e this one https://github.com/Bonfida/token-vesting/blob/master/js/src/dev.ts#L21

**Comment by dt1** [comment]
That account is not my wallet. Every time I run `yarn dev`, I get a different pubkey. I don't know where any of them come from or why they are being generated. I tried airdropping to them all, and it didn't matter because it would just generate a new one.

**Comment by dr497** [comment]
This account **must** be your wallet i.e the ones with the tokens to lock and it **must** be founded.

You just have to put the path to your private key in this variable https://github.com/Bonfida/token-vesting/blob/master/js/src/dev.ts#L20

The new accounts created each time with 0 SOL are the vesting accounts so it's normal that they have no SOL.

**Comment by dt1** [comment]
Looks like I had to do many other configs to pass this error. I'm not even sure if it works, alas, immediately slammed with another error.

Is there any place to ask questions about this stuff? Seems the discord doesn't work.

Anyways, I'm closing the ticket. Sorry to make a bother here.
