### ISSUE TITLE
Transaction simulation failed: Attempt to load a program that does not exist

### ISSUE THREAD

**Issue by chunghyunp** [Bonfida/token-vesting#32]
My issue is that I put the wrong program Id because of I'm testing on devnet but I cannot find where should I put the program Id for the devnet to pass the test.

<img width="1083" alt="스크린샷 2022-01-20 오전 10 44 11" src="https://user-images.githubusercontent.com/80745960/150247239-d9c064ca-2a8a-4070-8e4f-b7f67ce8fb1a.png">

**Comment by dr497** [comment]
The error message is pretty self explanatory, you are passing the wrong program id. You will find the devnet program id https://github.com/Bonfida/token-vesting/tree/master/js

**Comment by chunghyunp** [comment]
Hi. Thanks for the reply. I already find the program Id for the devnet which is `Hj9R6bEfrULLNrApMsKCEaHR9QJ2JgRtM381xgYcjFmQ`. but I can't find where should I revise the code to replace it. :(

**Comment by chunghyunp** [comment]
I found
