### ISSUE TITLE
Is there an api to undo Create linear vesting?

### ISSUE THREAD

**Issue by readygo77** [Bonfida/token-vesting#35]
Hi~
Is there an api to undo Create linear vesting?
(testing with cli)
If cancellation is possible, what happens to the tokens that have not been unlocked?

**Comment by dr497** [comment]
You cannot revoke vested tokens

**Comment by readygo77** [comment]
Is there any way to recover the tokens sent when creating linear vesting?

**Comment by readygo77** [comment]
> You cannot revoke vested tokens

Is there any way to recover the tokens sent when creating linear vesting?
