### ISSUE TITLE
Please how to get vesting info using getProgramAccounts

### ISSUE THREAD

**Issue by oasisMystre** [Bonfida/token-vesting#45]
```
  const accountInfo = await getProgramAccounts(
    connection,
    new PublicKey("HJbNNxXVtT4beZo4W15GmNKedp7MZ8tkdPcQurFarrQE"),
    32,
    TOKEN_VESTING_PROGRAM_ID,
  );
```

I have the following code. I want to be able to get all  vesting info for a particular wallet address

**Comment by Chocopieca** [comment]
Draw information in the transaction history and crawl it by staking
criteria ?


Пт, 22 марта 2024 г. в 01:13, Include caleb.fun ***@***.***>:

**Comment by dr497** [comment]
You can perform a `getProgramAccounts` request and filter on the `destination_address` using the token address of the user

**Comment by Chocopieca** [comment]
Thank you for answering

Пт, 22 марта 2024 г. в 06:53, DR497 ***@***.***>:

**Comment by oasisMystre** [comment]
Got this and was able to crawl and decode seed from the transaction data. 

Drawbacks

1. I need to keep getting transaction hash and call the parsed transaction RPC call to be able to extract seed from instruction data.
2. I don't know why the unlocked state is not kept in the contract info. 

Please I need to know the rust version and Solona CLI that can run the project. Keep getting dependencies error .
