### ISSUE TITLE
A bug or sumething? Can't settle the amount.

### ISSUE THREAD

**Issue by 43emre** [Bonfida/token-vesting#5]
Hi,
First of all I'm sorry if it's the wrong place to write up.
I'm new to the platform. I wanted to trade but I keep getting errors settling the amount since yesterday.
And apparently, there is not many people having the same issue because I couldn't find any on the internet posts.
I had an SS and attached it.
![Screen Shot 2021-05-15 at 13 20 40](https://user-images.githubusercontent.com/84228179/118357117-1c970500-b581-11eb-9fd6-c5fd1f003ccb.png)

Can you help me out please,
Emre.

**Comment by dr497** [comment]
This is the repo of a token vesting contract.

For this type of issue please ask on Telegram https://t.me/bonfidatg
