### ISSUE TITLE
Incorrect flag name

### ISSUE THREAD

**Issue by therealssj** [Bonfida/token-vesting#6]
For release schedule 
when parsing the input the cli looks for `release-times`
https://github.com/Bonfida/token-vesting/blob/0f655ef79fbdba44c41c70b2bedbcdfbd7313e9f/cli/src/main.rs#L326-L327

but when executing the function it looks for `release-heights`
https://github.com/Bonfida/token-vesting/blob/0f655ef79fbdba44c41c70b2bedbcdfbd7313e9f/cli/src/main.rs#L474

making the program un-useable atm

which one do you guys prefer?

**Comment by ellttBen** [comment]
Hello, thanks for pointing that out, will fix this ASAP.
