### ISSUE TITLE
Error when trying to unlock and change destination + token not released after the limit lock date

### ISSUE THREAD

**Issue by VictorLux** [Bonfida/token-vesting#8]
Hi,

Have an error when trying to unlock or change destination  + the lock date (June 21st 2021) passed but token is not released

What I did : 

I did lock a SPL token, on a specific token address, it works. Date to release June 21th 2021
I change destination to another address (not a derived one), It works.

I tried to unlock before June 21st 2021, error
I tried to change destination, error.

Date is now June 22th 2021, and on the token-vesting UI, token still locked.

Regards,
<img width="1338" alt="Capture d’écran 2021-06-22 à 08 24 03" src="https://user-images.githubusercontent.com/37399521/122874473-518e3880-d333-11eb-86d0-fc87aacca526.png">
<img width="594" alt="Capture d’écran 2021-06-22 à 08 24 25" src="https://user-images.githubusercontent.com/37399521/122874493-57841980-d333-11eb-8c14-4e75f528837a.png">

**Comment by dr497** [comment]
What's the contract seed? Do you have the signatures of your previous transactions?

**Comment by VictorLux** [comment]
yes here is the signature of the change destination : 
https://explorer.solana.com/tx/3C9fTg5Wi1QLaAAYwH6Q7AjxwtxWRZtTzXdrFpk9WjdLVVuiSztXkYwPsu1MwwQd6eG4cNYoWRHdV23XaZrSfRzZ

will dm you on discord the seed ;-)
